project:
  type: website
  output-dir: docs/
  render:
    - "*.qmd"
    - "!posts_draft/"

website:
  favicon: logo.png
  title: "Raphael Saldanha"
  page-navigation: true
  back-to-top-navigation: true
  google-analytics: "G-2M7VLSRDCB"
  page-footer:
    background: light
    left: "Copyright 2024, Raphael Saldanha"
    right:
      - icon: github
        href: https://github.com/rfsaldanha
      - icon: mastodon
        href: https://fosstodon.org/@rfsaldanha
  navbar:
    logo: logo.png
    logo-alt: Raphael Saldanha
    search: true
    right:
      - cv.qmd
      - projects.qmd
      - code.qmd
      - data.qmd
      - publications.qmd
      - talks.qmd
      - photos/photos.qmd
      - blog.qmd

format:
  html:
    theme:
      - styles.scss
    mainfont: Nunito
    toc: true

editor: visual
