project:
  type: website
  output-dir: docs/
  render: 
    - "!posts_draft/"

website:
  title: "Raphael Saldanha"
  page-navigation: true
  back-to-top-navigation: true
  google-analytics: "G-2M7VLSRDCB"
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/)."
  navbar:
    search: true
    left:
      - projects.qmd
      - code.qmd
      - data.qmd
      - publications.qmd
      - cv.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    toc: true

editor: visual
